apiVersion: v1
kind: Service
metadata:
  name: retail-store-cart-service
  labels:
    app: retail-store-cart
spec:
  selector:
    app: retail-store-cart
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort